version: '2'
services:
  web:
       build:
               context: ./php/online-shopping-system
               dockerfile: Dockerfile_update_webapp
       image: nibha1611/bdaecommphp:latest
       container_name: php_app_1
       depends_on:
         - db
       ports:
         - 9002:80
  db:
          build:
                  context: ./php/online-shopping-system/database
                  dockerfile: Dockerfile_db
          image: nibha1611/bdaecommdb:latest
          container_name: mysqlinew
          command: --default-authentication-plugin=mysql_native_password
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: edureka
            MYSQL_PASSWORD: admin
          ports:
           - 6036:3306
